version: '3.2'

services:
  proxy:
    image: nginx:alpine
    networks:
      - frontend
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  apache1:
    build: './apache1/monsite/'
    depends_on:
      - php
      - mariadb
    networks:
      - frontend
      - backend1
    volumes:
      - ./apache1/monsite/html:/srv/htdocs
  apache2:
    build: './apache2/monsite/'
    depends_on:
      - php2
      - mariadb2
    networks:
      - frontend
      - backend2
    volumes:
      - ./apache2/monsite/html:/srv/htdocs
  php:
    build: './apache1/php/'
    networks:
      - backend1
    volumes:
      - ./apache1/monsite/html:/srv/htdocs
  mariadb:
    image: mariadb
    networks:
      - backend1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  php2:
    build: './apache2/php/'
    networks:
      - backend2
    volumes:
      - ./apache2/monsite/html:/srv/htdocs
  mariadb2:
    image: mariadb
    networks:
      - backend2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

networks:
  frontend:
  backend1:
  backend2:
